command_key = ":"
initial_screen = "library"
use_nerdfont = true
flip_status_indicators = true
audio_cache = true
audio_cache_size = 100 
notify = true
bitrate = 320
gapless = true
shuffle = true
repeat = "playlist"
playback_state = "Paused"
hide_display_name = false
